// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean):Promise<string>;
